new_input: new_default_value
input_groups:
  '1':
    group_name: All Conditions
    group_conditions:
    - rain_a_clear_v_clear
    - rain_a_clear_v_noisy
    - rain_a_noisy_v_clear
    - rock_a_clear_v_clear
    - rock_a_clear_v_noisy
    - rain_a_noisy_v_noisy
    - rock_a_noisy_v_clear
    - rock_a_noisy_v_noisy
source_files: YAJ_demo-20211203-112740.fst
baseline_time:
- -1
- 0
project_name: Reliability
distance_method: manhattan
hclust_method: ward.D2
input_nclusters: 2
roi_options:
  variable: Hemisphere
  values: right
  roi_ignore_gyrus_sulcus: no
  roi_ignore_hemisphere: no
analysis_event: Trial_Onset
power_unit: Pct_Change_Amplitude
optim_clusters:
  max_nclusters: 8.0
  methods: default
analysis_time_window:
- -1
- 3
debug: no
cluster_method: H-Clust
plot_time_window:
- -1
- 3
color_scheme: Dark2
use_baseline: yes
mds_distance: manhattan
